image: node:latest

before_script:

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

testing_parto:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - echo "testing Parto..."
    - echo $NODE_ENV
    - npm install
    - pm2 stop development.js
    # - npx sequelize-cli db:drop --charset utf8mb4 --collate utf8mb4_persian_ci 
    # - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    # - npx sequelize-cli db:migrate
    # - npx sequelize-cli db:seed:all
    # - npx sequelize db:seed --seed 20210408115203-new_health_tracking_category.js
    # - npx sequelize db:seed --seed 20210408115224-new_health_tracking_option.js
    # -  npx sequelize db:seed --seed 20210509195107-message_category.js
    # -  npx sequelize db:seed --seed 20200521042512-translation_key_seeds2.js
    #   -  npx sequelize db:seed --seed 20210817073746-discount_per_service.js
    # - npm test
    - echo "testing succsecfull  "
  only:
    - test

deploy_staging_parto:
  stage: deploy
  variables:
    NODE_ENV: "test"
    NODE_PORT: 2216
  environment:
    name: staging
    url: https://dev.parto.app

  script:
    - echo "Deploy to staging server ..."
    - PORT=2216
    # - pm2 start development.js
    - pm2 startOrRestart ecosystem.config.js --only "development"
    - echo "deploy_staging succesfull"
    # - pm2 logs

  only:
    - test

deploy_prod_parto:
  stage: deploy
  variables:
    NODE_ENV: "production"
    NODE_PORT: 2218
  script:
    - echo "Deploy to production server ..."
    - npm install
    - PORT=2218
    # - npx sequelize-cli db:migrate 
    # - pm2 start app.js
    - pm2 startOrRestart ecosystem.config.js --only "app"
    - echo "Deploy to production server Successful"
    #- pm2 logs

  environment:
    name: production
    url: https://api.parto.app
  when: manual
  only:
    - master
