image: node:latest

before_script:

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

testing_parto:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - echo "testing Parto..."
    - echo $NODE_ENV
    - npm install
    - pm2 stop development.js
    # - npx sequelize-cli db:drop --charset utf8mb4 --collate utf8mb4_persian_ci 
    - npx sequelize migration:create --name rename-column-partner-to-partner_id-in-user
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    - npm test
    - echo "testing succsecfull  "
  only:
    - test

deploy_staging_parto:
  stage: deploy
  variables:
    NODE_ENV: "test"
    NODE_PORT: 2216
  environment:
    name: staging
    url: https://dev.parto.app

  script:
    - echo "Deploy to staging server ..."
    - PORT=2216
    - pm2 restart development.js
    - echo "deploy_staging succesfull"
    # - pm2 logs

  only:
    - test

deploy_prod_parto:
  stage: deploy
  variables:
    NODE_ENV: "production"
    NODE_PORT: 2218
  script:
    - echo "Deploy to production server ..."
    - npm install
    - PORT=2218
    - npx sequelize-cli db:migrate
    - pm2 restart app.js
    - echo "Deploy to production server Successful"
    # - pm2 logs

  environment:
    name: production
    url: https://api.parto.app
  when: manual
  only:
    - master
