image: node:latest
stages:
    - run
    - build
    - test
cache:
  paths:
    - node_modules/
running_parto:
  stage: run
  variables:
   NODE_ENV: "test"
  script: 
    - echo "Running Parto..."
    - echo $NODE_ENV
    - npm install
    - killall node || echo "No other instnaces is running."
    - node app.js
