image: node:latest
stages:
    - run
    - build
    - test
cache:
  paths:
    - node_modules/
running_parto:
  stage: run
  variables:
   NODE_ENV: "test"
  script: 
    - echo "Running Parto..."
    - echo $NODE_ENV
    - killall node || echo "No other instnaces is running."
    - npm install
    - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    - npm start
testing_parto:
    stage: test
    NODE_ENV: "test"
    script:
         - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
         - npx sequelize-cli db:migrate
         - npx sequelize-cli db:seed:all
         - npm test
       
    