image: node:latest

before_script:
   - pm2 stop pm2-manage.json

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

testing_parto:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - pm2 delete portPWA2214
    - echo "testing Parto..."
    - echo $NODE_ENV
    - npm install
    - npx sequelize-cli db:drop --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    - npm test
    - echo "testing succsecfull"

deploy_staging_parto:
  stage: deploy
  variables:
    NODE_ENV: "test"
  environment:
    name: staging
    url: https://api.partobanoo.com

  script:
     - echo "Deploy to staging server ..."
     - pm2 start pm2-manage.json
     # - npm run build
     # - pm2 start pwa.js
     #- npm run dev
     #- pm2 start npm --name "pwa" -- start
    
     - echo "deploy_staging succesfull"

  only:
    - master

deploy_prod_parto:
  stage: deploy
  variables:
    NODE_ENV: "production"
  script:
    - echo "Deploy to production server ..."
    - npm install
    - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    - pm2 start app.js
    - echo "Deploy to production server Succdsfull"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
