image: node:latest

before_script:
 

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/

testing_parto:
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - echo "testing Parto..."
    - echo $NODE_ENV
    - npm install
    - npx sequelize-cli db:drop --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    # - pm2 stop development.js
    - npm test
    - echo "testing succsecfull"
  only:
    - test

deploy_staging_parto:
  stage: deploy
  variables:
    NODE_ENV: "test"
    NODE_PORT: 2216
  environment:
    name: staging
    url: https://dev.partobanoo.com

  script:
     - echo "Deploy to staging server ..."
     - PORT=2216
     - pm2 start development.js
     - echo "deploy_staging succesfull"

  only:
    - test

deploy_prod_parto:
  stage: deploy
  variables:
    NODE_ENV: "production"
    NODE_PORT: 2218
  script:
    - echo "Deploy to production server ..."
    - npm install
    - npx sequelize-cli db:drop --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:create --charset utf8mb4 --collate utf8mb4_persian_ci
    - npx sequelize-cli db:migrate
    - npx sequelize-cli db:seed:all
    - PORT=2218
    - pm2 start pm2-manage.json
    - echo "Deploy to production server Succdsfull"
  environment:
    name: production
    url: https://api.partobanoo.com
  when: manual
  only:
    - master
