image: node:latest
stages:
    - run
    - build
    - test
cache:
  paths:
    - node_modules/
running_parto:
  stage: run
  script: 
    - echo "Running Parto..."
    - npm install
    - nodemon app.js
