image: node:latest
stages:
    - run
    - build
    - test
cache:
  paths:
    - node_modules/
running_parto:
  stage: run
  script: 
    - echo "Running Parto..."
    - export NODE_ENV=test
    - echo $NODE_ENV
    - npm install
    - node app.js
