
swagger: "2.0"
info: {
    title: 'Parto Swagger API',
    version: '1.0.0',
    description: 'Endpoints to test parto app api',
},
host: "https://dev.parto.app"
basePath: '/'
securityDefinitions: {
    bearerAuth: {
    type: 'apiKey',
    name: 'Authorization',
    scheme: 'bearer',
    in: 'header',
    }
}
 
  
const options = {
    swaggerDefinition,
    apis: ['./routes/*.js'],
  };