openapi: 3.0.0
info:
  title: parto api
  description: api that use in app parto
  version: 0.1.9
servers:
  - url: https://api.partobanoo.com/api-docs
    description: Opartobanoo api server
paths:
  /signUp/:lang:
    post:
      summary: sign up user with email .
      description: 
      requestBody:
        content:
          application/json:
            schema:      # Request body contents
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
              password:  
                  type: string
               example:         
              # Properties of a referenced object
                  email: example.gmail.com
                  name: admin
                  password: 1234
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string